# Generated by Django 2.2.5 on 2019-09-18 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20190917_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Artigo', 'verbose_name_plural': 'Artigos'},
        ),
    ]
